<a href="https://colab.research.google.com/github/SEAFromJahu/SEA_Alura_Lesson4_Project/blob/main/SEA_Alura_Lesson4_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

INSTALANDO O SDK DO GOOGLE

In [1]:
pip install -q -U google-generativeai

IMPORTANDO GOOGLE GENERATIVEAI...CONFIGURANDO API_KEY PARA USO...CRIANDO UM CLIENTE DA GENERATIVEAI

In [2]:
import google.generativeai as genai

from google.colab import userdata
GOOGLE_API_KEY =userdata.get('GOOGLE_API_KEY')
genai.configure(api_key=GOOGLE_API_KEY)

CRIANDO UM CLIENTE DO GEMINI PARA UTILIZAR NO PROJETO

In [3]:
genai.configure(api_key=GOOGLE_API_KEY)

TIPOS DE SAFETY_SETTINGS: "BLOCK_NONE", "BLOCK_FEW","BLOCK_SOME", "BLOCK_MOST" O DEFAULT É BLOCK_SOME.

In [4]:
generation_config = {
    "candidate_count": 1,
    "temperature": 0,
}

safety_settings = {
    "HARASSMENT": "BLOCK_NONE",
    "HATE": "BLOCK_NONE",
    "SEXUAL": "BLOCK_NONE",
    "DANGEROUS": "BLOCK_NONE",
}

INICIALIZAR O MODELO GENERATIVO

In [5]:
model = genai.GenerativeModel('gemini-1.5-pro-latest',
                              generation_config=generation_config,
                              safety_settings=safety_settings)

A API Gemini POSSIBILITA CRIAR UM CHATBOT, INICIANDO O MESMO...

In [6]:
chat = model.start_chat(history=[])

SOLICITA QUE O USUÁRIO DIGITE PERGUNTAS perguntas e as responde até que o usuário digite "fim"

In [ ]:
prompt = input("Esperando prompt: ")
while prompt != "fim":
  response = chat.send_message(prompt)
  print("Resposta: ", response.text, "\n")
  prompt = input("Esperando prompt: ")

Esperando prompt: Sabendo-se que: A faixa de frequência audível para humanos é normalmente entre 20 Hz e 20.000 Hz. Baixas frequências (20 Hz - 200 Hz): Essas frequências são sentidas mais como vibrações do que como sons e são produzidas por objetos grandes como terremotos, trovões e graves profundos. Médias frequências (200 Hz - 2.000 Hz): Esta faixa contém a maioria dos sons fundamentais da fala humana e de muitos instrumentos musicais. Altas frequências (2.000 Hz - 20.000 Hz): Sons agudos, como assobios, canto de pássaros e harmônicos de instrumentos musicais, caem nesta faixa. Embora a faixa de audição humana seja frequentemente descrita como 20 Hz a 20.000 Hz, não é tão simples quanto contar os números entre esses dois limites. Isso ocorre porque a frequência é medida em uma escala logarítmica, não linear. Calculando o Número de Frequências Audíveis Embora seja tecnicamente impossível contar o número exato de frequências audíveis entre 20 Hz e 20.000 Hz devido à natureza contínua 

Montagem do prompt que será utilizado acima como questão a ser respondida.

Sabendo-se que:
A faixa de frequência audível para humanos é normalmente entre 20 Hz e 20.000 Hz.
Baixas frequências (20 Hz - 200 Hz): Essas frequências são sentidas mais como vibrações do que como sons e são produzidas por objetos grandes como terremotos, trovões e graves profundos.
Médias frequências (200 Hz - 2.000 Hz): Esta faixa contém a maioria dos sons fundamentais da fala humana e de muitos instrumentos musicais.
Altas frequências (2.000 Hz - 20.000 Hz): Sons agudos, como assobios, canto de pássaros e harmônicos de instrumentos musicais, caem nesta faixa.
Embora a faixa de audição humana seja frequentemente descrita como 20 Hz a 20.000 Hz, não é tão simples quanto contar os números entre esses dois limites. Isso ocorre porque a frequência é medida em uma escala logarítmica, não linear.
Calculando o Número de Frequências Audíveis Embora seja tecnicamente impossível contar o número exato de frequências audíveis entre 20 Hz e 20.000 Hz devido à natureza contínua da escala de frequência, podemos aproximar um número usando o conceito de discriminação de frequência.
A discriminação de frequência refere-se à nossa capacidade de distinguir entre duas frequências ligeiramente diferentes. Os humanos geralmente conseguem discriminar entre frequências que diferem em cerca de 0,3% em uma faixa de frequência moderada.
Com essa informação, podemos fazer uma estimativa aproximada: Dividimos a faixa de frequência em partes menores: Dividiríamos a faixa de 20 Hz a 20.000 Hz em pequenos intervalos que diferem em 0,3%.
Número de intervalos = (log2(f2) - log2(f1)) / log2(1 + d) Onde:f1 é a frequência mais baixa (20 Hz)f2 é a frequência mais alta (20.000 Hz)d é a diferença justa perceptível (0,003)
Calculamos o número de intervalos -> Número de intervalos = (log2(20.000) - log2(20)) / log2(1,003) ≈ 3283.
Combinações de sequencias de frequências sonoras perceptíveis são finitas.
Com 3283 intervalos obtemos 2^3283 combinações possíveis de frequência sonoras perceptíveis com tons puros.
Na realidade, a maioria dos sons que ouvimos (música, fala, natureza) são compostos por múltiplas frequências simultâneas, criando timbres e texturas complexas.
A intensidade (volume) e a duração de cada frequência influenciam a percepção. Um mesmo tom em diferentes volumes ou durações soa distinto.
A presença de certas frequências pode mascarar outras, tornando-as inaudíveis.
A música se baseia em relações harmônicas entre frequências, e não em combinações aleatórias.
Nosso cérebro não processa cada frequência individualmente. A percepção se dá de forma integrada, com foco em padrões e mudanças no espectro sonoro.
Podemos estimar o número de intervalos de frequência discrimináveis. Calcular o número total de combinações "perceptíveis" é um desafio complexo.
O cérebro humano não analisa cada frequência isoladamente. A percepção é holística, focando em padrões e mudanças no espectro sonoro.
O número de combinações de frequências puras  2^3283 é um número astronômico, mas finito.
A IA esta ai para mensurar grandezas que são impossíveis aos humanos.
Considerando todos os inputs anteriores acima, qual é o solução possível para se obter a resposta a questão?